config/routes.rb
Rails.application.routes.draw do
  get "/authors/new", to: "authors#new", as: "new_author"
  get "/authors/:id", to: "authors#show", as: "author"
  post "/authors", to: "authors#create"

  get "/posts/:id", to: "posts#show", as: "post"
  get "/posts/:id/edit", to: "posts#edit", as: "edit_post"
  patch "/posts/:id", to: "posts#update"
end

app/models/author.rb
class Author < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def show
    @author = Author.find(params[:id])
  end

  def new
  end

  def create
    @author = Author.create!(author_params)

    redirect_to author_path(@author)
  end

  private

  def author_params
    params.permit(:email, :name)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post!, only: [:show, :edit, :update]

  def show
  end

  def edit
  end

  def update
    @post.update(post_params)

    redirect_to post_path(@post)
  end

  private

  def post_params
    params.permit(:category, :content, :title)
  end

  def set_post!
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authors/new.html.erb
<h2>Create an Author</h2>
<%= form_tag authors_path, method: "post" do %>
  <div class="field">
    <%= label_tag "name", "Name" %>
    <%= text_field_tag "name" %>
  </div>
  <div class="field">
    <%= label_tag "email", "Email" %>
    <%= text_field_tag "email" %>
  </div>
  <%= submit_tag "Create Author" %>
<% end %>

app/views/authors/show.html.erb
<h2><%= @author.name %></h2>
<a href="mailto:<%= @author.email %>"><%= @author.email %></a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ValidationsInControllerActionsRailsLab</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<h2>Editing "<%= @post.title %>"</h2>
<%= form_tag post_path(@post), method: "patch" do %>
  <div class="field">
    <%= label_tag "title", "Title" %>
    <%= text_field_tag "title", @post.title %>
  </div>
  <div class="field">
    <%= label_tag "category", "Category" %>
    <p>Must be either "Fiction" or "Non-Fiction".</p>
    <%= text_field_tag "category", @post.category %>
    <p>
      Please type carefully as our top scientists are working around the clock to
      enable state-of-the-art dropdown technology for this form field.
    </p>
  </div>
  <div class="field">
    <%= label_tag "content", "Content" %>
    <br />
    <%= text_area_tag "content", @post.content %>
  </div>
  <%= submit_tag "Update" %>
<% end %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<%= link_to "edit", edit_post_path(@post) %>
<p>A <%= @post.category %> post.</p>
<hr />
<p><%= @post.content %></p>